// src/contexts/LanguageContext.tsx
import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'si' | 'ta';

const translations = {
  en: {
    "police.dept": "Sri Lanka Police Department",
    "system.title": "Traffic Fine Management System",
    "card.pay.title": "Pay Traffic Fine",
    "card.pay.desc": "Pay your traffic fine online securely with your reference number.",
    "card.pay.cta": "Enter Portal",
    "card.search.title": "Record Lookup",
    "card.search.desc": "Lost your ticket? Search pending fines by NIC or Vehicle No.",
    "card.search.cta": "Search Records",
    "card.admin.title": "Admin Dashboard",
    "card.admin.desc": "Senior personnel monitoring & national overview.",
    "card.admin.cta": "Official Access",
    "footer": "Powered by Ministry of Public Administration • Sri Lanka • 2026", // <-- ADDED COMMA HERE
    "card.dispute.title": "Dispute a Fine",
    "card.dispute.desc": "Submit a formal appeal and upload digital evidence.",
    "card.dispute.cta": "Open Tribunal",
    "404.title": "404",
    "404.message": "This page is not on file.",
    "404.return": "Return Home",
    "pay.portal.title": "Traffic Fine Payment Portal",
    "pay.header.subtitle": "Sri Lanka Police",
    "officer.login.title": "Officer Login",
    "officer.login.subtitle": "Traffic Fine Issuance System",
    "officer.username": "Username / Badge ID",
    "officer.password": "Password",
    "officer.login.btn": "Login",
    "officer.authenticating": "Authenticating...",
    "officer.access.denied": "Access denied. Officer credentials required.",
    "officer.auth.failed": "Authentication failed",
    "pay.verify.step": "Verify Fine",
    "pay.reference": "Reference Number",
    "pay.category": "Category",
    "pay.verify.btn": "Verify",
    "pay.error.required": "Please enter both Reference Number and Category.",
    "pay.verify.title": "Fine Verification",
    "pay.ref.label": "Fine Reference Number",
    "pay.ref.placeholder": "e.g., TF-2026-00000",
    "pay.cat.label": "Fine Category Identifier",
    "pay.cat.placeholder": "e.g. SPD, SIG, LIC, PKG, DRK",
    "pay.scan": "Smart Scan",
    "pay.verifying": "Verifying…",
    "pay.finedetails": "Fine Details",
    "pay.detail.ref": "Reference #",
    "pay.detail.violation": "Violation",
    "pay.detail.amount": "Amount Due",
    "pay.detail.issuedby": "Issued By",
    "pay.detail.date": "Date",
    "pay.detail.location": "Location",
    "pay.cancel": "Cancel",
    "pay.proceed": "Proceed to Payment →",
    "pay.payment.title": "Payment Information",
    "pay.cardholder": "Cardholder Name",
    "pay.cardholder.placeholder": "As printed on card",
    "pay.cardnumber": "Card Number",
    "pay.cardnumber.placeholder": "0000 0000 0000 0000",
    "pay.expiry": "Expiry (MM/YY)",
    "pay.expiry.placeholder": "MM/YY",
    "pay.cvv": "CVV",
    "pay.cvv.placeholder": "•••",
    "pay.phone": "Mobile Number for Receipt & SMS",
    "pay.phone.placeholder": "07X XXX XXXX",
    "pay.totalamount": "Total Amount",
    "pay.authorize": "Authorize Payment",
    "pay.processing": "Processing...",
    "pay.verify.error": "Please complete all payment details.",
    "pay.success.title": "Payment Successful",
    "pay.receipt": "Official Receipt",
    "pay.receipt.no": "Receipt #",
    "pay.receipt.ref": "Reference",
    "pay.receipt.paid": "Amount Paid",
    "pay.receipt.datetime": "Date & Time",
    "pay.receipt.txnid": "Transaction ID",
    "pay.receipt.footer": "Sri Lanka Police • Traffic Division",
    "pay.scanner.title": "AI Ticket Scanner",
    "pay.scanner.status": "Align the ticket in the frame and capture.",
    "pay.scanner.reading": "AI Engine reading text...",
    "pay.scanner.capture": "Capture & Scan Ticket",
  },
  si: {
    "police.dept": "ශ්‍රී ලංකා පොලිස් දෙපාර්තමේන්තුව",
    "system.title": "රථවාහන දඩ කළමනාකරණ පද්ධතිය",
    "card.pay.title": "රථවාහන දඩ ගෙවන්න",
    "card.pay.desc": "ඔබගේ යොමු අංකය සමඟ මාර්ගගතව දඩ මුදල් ගෙවන්න.",
    "card.pay.cta": "පිවිසෙන්න",
    "card.search.title": "වාර්තා සෙවීම",
    "card.search.desc": "ජාතික හැඳුනුම්පත හෝ වාහන අංකය මගින් දඩ වාර්තා සොයන්න.",
    "card.search.cta": "වාර්තා සොයන්න",
    "card.admin.title": "පරිපාලක පුවරුව",
    "card.admin.desc": "ජ්‍යෙෂ්ඨ නිලධාරීන්ගේ අධීක්ෂණය සහ ජාතික දළ විශ්ලේෂණය.",
    "card.admin.cta": "නිල ප්‍රවේශය",
    "footer": "රාජ්‍ය පරිපාලන අමාත්‍යාංශය මගින් බලගන්වා ඇත • ශ්‍රී ලංකාව • 2026", // <-- ADDED COMMA HERE
    "card.dispute.title": "දඩ අභියාචනය",
    "card.dispute.desc": "විධිමත් අභියාචනයක් ඉදිරිපත් කර ඩිජිටල් සාක්ෂි උඩුගත කරන්න.",
    "card.dispute.cta": "විවෘත කරන්න",
    "404.title": "404",
    "404.message": "මෙම පිටුව ගොනුවේ නොමැත.",
    "404.return": "මුල් පිටුවට ආපසු යන්න",
    "pay.portal.title": "රථවාහන දඩ ගෙවීම් පෝර්තලය",
    "pay.header.subtitle": "ශ්‍රී ලංකා පොලිස්",
    "officer.login.title": "නිලධාරී ලොගින්",
    "officer.login.subtitle": "රථවාහන දඩ නිකුත් පද්ධතිය",
    "officer.username": "පරිශීලක නාමය / බෝ අංකය",
    "officer.password": "මුරපදය",
    "officer.login.btn": "ලොගින්",
    "officer.authenticating": "බලාපොරොත්තු කරමින් ඇත...",
    "officer.access.denied": "ප්‍රවේශ ප්‍රතික්ෂේප කරන ලදී. නිලධාරී සනාසxavier අවශ්‍ය වේ.",
    "officer.auth.failed": "සත්‍යාපනය අසාර්థක විය",
    "pay.verify.step": "දඩ සත්‍යාපනය",
    "pay.reference": "යොමු අංකය",
    "pay.category": "කාණ්ඩය",
    "pay.verify.btn": "සත්‍යාපනය",  
    "pay.error.required": "කරුණාකර සඳහන් අංකය සහ කාණ්ඩය යන දෙකම ඇතුල් කරන්න.",
    "pay.verify.title": "දඩ සත්‍යාපනය",
    "pay.ref.label": "දඩ සඳහන් අංකය",
    "pay.ref.placeholder": "උදා, TF-2026-00000",
    "pay.cat.label": "දඩ කාණ්ඩ හඳුනාගැනීමක්",
    "pay.cat.placeholder": "උදා SPD, SIG, LIC, PKG, DRK",
    "pay.scan": "ස්මාර්ට් ස්කෑන්",
    "pay.verifying": "සත්‍යාපනය කරමින්...",
    "pay.finedetails": "දඩ විස්තර",
    "pay.detail.ref": "සඳහන් #",
    "pay.detail.violation": "උල්ලංඝනය",
    "pay.detail.amount": "ගෙවිය යුතු මුදල",
    "pay.detail.issuedby": "නිකුත් කරන ලද්දේ",
    "pay.detail.date": "දිනය",
    "pay.detail.location": "ස්ථානය",
    "pay.cancel": "අවලංඝනය කරන්න",
    "pay.proceed": "ගෙවීමට ඉදිරි ගිය →",
    "pay.payment.title": "ගෙවීම් තොරතුරු",
    "pay.cardholder": "කාඩ් ակර්තන කරුගේ නම",
    "pay.cardholder.placeholder": "කාඩ් එකේ ලියා ඇති පරිදි",
    "pay.cardnumber": "කාඩ් අංකය",
    "pay.cardnumber.placeholder": "0000 0000 0000 0000",
    "pay.expiry": "සීමාවස්‍යතා (MM/YY)",
    "pay.expiry.placeholder": "MM/YY",
    "pay.cvv": "CVV",
    "pay.cvv.placeholder": "•••",
    "pay.phone": "ගිණුම් සඳහා ජංගම අංකය සහ SMS",
    "pay.phone.placeholder": "07X XXX XXXX",
    "pay.totalamount": "සම්පූර්ණ මුදල",
    "pay.authorize": "ගෙවීම අවසර දෙන්න",
    "pay.processing": "සකස් කරමින්...",
    "pay.verify.error": "කරුණාකර සියලු ගෙවීම් විස්තර සම්පූර්ණ කරන්න.",
    "pay.success.title": "ගෙවීම සාර්థක",
    "pay.receipt": "නිල ගිණුම්",
    "pay.receipt.no": "ගිණුම් #",
    "pay.receipt.ref": "සඳහන්",
    "pay.receipt.paid": "ගෙවන ලද මුදල",
    "pay.receipt.datetime": "දිනය සහ වේලාව",
    "pay.receipt.txnid": "ගනුදෙනු ID",
    "pay.receipt.footer": "ශ්‍රී ලංකා පොලිස් • ගිණුම් බිඹුව",
    "pay.scanner.title": "AI ටිකට් ස්කෑනර්",
    "pay.scanner.status": "ටිකට් රාමුවේ පිහිටුවා සිටින්න.",
    "pay.scanner.reading": "AI එංජින් පාඩ්ය කියවමින්...",
    "pay.scanner.capture": "ටිකට් ග්‍රහණ කරන්න සහ ස්කෑන් කරන්න",
    "pay.receipt.paid": "ගෙවන ලද මුදල",
    "pay.receipt.datetime": "දිනය සහ වේලාව",
    "pay.receipt.txnid": "ගනුදෙනු ID",
    "pay.receipt.footer": "ශ්‍රී ලංකා පොලිස් • ගිණුම්",
    "pay.scanner.title": "AI ටිකට් ස්කෑනර්",
    "pay.scanner.status": "ටිකට් රාමුවේ පිහිටුවා සිටින්න.",
    "pay.scanner.reading": "AI පාඩ්ය කියවමින්...",
   

  },
  ta: {
    "police.dept": "இலங்கை பொலிஸ் திணைக்களம்",
    "system.title": "போக்குவரத்து அபராத முகாமைத்துவ அமைப்பு",
    "card.pay.title": "அபராதம் செலுத்த",
    "card.pay.desc": "உங்கள் குறிப்பு எண்ணுடன் ஆன்லைனில் அபராதம் செலுத்துங்கள்.",
    "card.pay.cta": "உள்நுழைக",
    "card.search.title": "பதிவுகளை தேடு",
    "card.search.desc": "அடையாள அட்டை அல்லது வாகன எண் மூலம் அபராதங்களை தேடுங்கள்.",
    "card.search.cta": "பதிவுகளை தேடு",
    "card.admin.title": "நிர்வாகி டாஷ்போர்டு",
    "card.admin.desc": "மூத்த அதிகாரிகளின் கண்காணிப்பு மற்றும் தேசிய கண்ணோட்டம்.",
    "card.admin.cta": "அதிகாரப்பூர்வ அணுகல்",
    "footer": "பொது நிர்வாக அமைச்சகத்தால் இயக்கப்படுகிறது • இலங்கை • 2026", // <-- ADDED COMMA HERE
    "card.dispute.title": "அபராதம் மேல்முறையீடு",
    "card.dispute.desc": "முறையான மேல்முறையீட்டைச் சமர்ப்பித்து டிஜிட்டல் சான்றுகளைப் பதிவேற்றவும்.",
    "card.dispute.cta": "திறக்க",
     "404.title": "404",
    "404.message": "இந்தப் பக்கம் கோப்பில் இல்லை.",
    "404.return": "முகப்புக்குத் திரும்பு",
    "pay.portal.title": "போக்குவரத்து அபராத செலுத்தல் போர்டல்",
    "pay.header.subtitle": "இலங்கை பொலிஸ்",
    "officer.login.title": "அதிகாரி உள்நுழைவு",
    "officer.login.subtitle": "போக்குவரத்து அபராத வெளியீட்டு அமைப்பு",
    "officer.username": "பயனர்பெயர் / பேஜ் ID",
    "officer.password": "கடவுச்சொல்",
    "officer.login.btn": "உள்நுழைக",
    "officer.authenticating": "சரிபார்க்கிறது...",
    "officer.access.denied": "அணுகல் மறுக்கப்பட்டது. அதிகாரி சான்றுதாபனம் தேவை.",
    "officer.auth.failed": "சரிபார்ப்பு தோல்வியடைந்தது",
    "pay.verify.step": "அபராதம் சரிபார்ப்பு",
    "pay.reference": "குறிப்பு எண்",
    "pay.category": "வகைப்பாடு",
    "pay.verify.btn": "சரிபார்ப்பு",
    "pay.error.required": "குறிப்பு எண் மற்றும் வகைப்பாடு இரண்டையும் உள்ளிடவும்.",
     "pay.ref.label": "அபராதக் குறிப்பு எண்",
    "pay.ref.placeholder": "உ.கா. TF-2026-00000",
    "pay.cat.label": "அபராத வகைப்பாட ஐடென்டிஃபயர்",
    "pay.cat.placeholder": "உ.கா SPD, SIG, LIC, PKG, DRK",
    "pay.scan": "ஸ்மார்ட் ஸ்கேன்",
    "pay.verifying": "சரிபார்க்கிறது…",
    "pay.finedetails": "அபராத விவரங்கள்",
    "pay.detail.ref": "குறிப்பு #",
    "pay.detail.violation": "மீறல்",
    "pay.detail.amount": "செலுத்த வேண்டிய தொகை",
    "pay.detail.issuedby": "வெளியிட்டவர்",
    "pay.detail.date": "தேதி",
    "pay.detail.location": "இடம்",
    "pay.cancel": "ரத்து",
    "pay.proceed": "பணம் செலுத்துவதற்கு செல்லலாம் →",
    "pay.payment.title": "பணம் செலுத்துவதற்கான தகவல்",
    "pay.cardholder": "கிரெடிட் கார்டு வைத்திருப்பவரின் பெயர்",
    "pay.cardholder.placeholder": "கার்டில் அச்சிடப்பட்ட விதம்",
    "pay.cardnumber": "கার்ட எண்",
    "pay.cardnumber.placeholder": "0000 0000 0000 0000",
    "pay.expiry": "விலக்ஸ் (MM/YY)",
    "pay.expiry.placeholder": "MM/YY",
    "pay.cvv": "CVV",
    "pay.cvv.placeholder": "•••",
    "pay.phone": "ரசீது மற்றும் SMS க்கான செல்போன் எண்",
    "pay.phone.placeholder": "07X XXX XXXX",
    "pay.totalamount": "மொத்த அளவு",
    "pay.authorize": "பணம் செலுத்தலை அনுமதி",
    "pay.processing": "செயலாக்குகிறது...",
    "pay.verify.error": "தயவுசெய்து அனைத்து பணம் செலுத்தும் விவரங்களைச் செயல்படுத்தவும்.",
    "pay.success.title": "பணம் செலுத்தல் வெற்றிகரமாக நிறைவடைந்தது",
    "pay.receipt": "அதிகாரப்பூர்வ ரசீது",
    "pay.receipt.no": "ரசீது #",
    "pay.receipt.ref": "குறிப்பு",
    "pay.receipt.paid": "செலுத்திய தொகை",
    "pay.receipt.datetime": "தேதி மற்றும் நேரம்",
    "pay.receipt.txnid": "பேনாடை ID",
    "pay.receipt.footer": "இலங்கை பொலிஸ் • பணி பிரிவு",
    "pay.scanner.title": "AI டிக்கெட் ஸ்கேனர்",
    "pay.scanner.status": "டிக்கெட்டை ফ్రేમ్‌లో தఈక్క సేవా",
    "pay.scanner.reading": "AI என்జిన் உரைத்தைப் படிக்கிறது...",
    "pay.scanner.capture": "டிக్్సेటను సుพ్తcapture & స్కాన్ చేయండి",
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations['en']) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: keyof typeof translations['en']) => {
    return translations[language][key] || translations['en'][key];
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within a LanguageProvider");
  return context;
};