# PostgreSQL Database Configuration (Session Pooler)
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.wvyrwqdvinyxnzwcrsgy
spring.datasource.password=Z@H_$#bcE87$$#V
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#psql.exe -U postgres -d traffic_fines_db
#    
